FROM python:3.9-slim-buster

ARG ZSH_IN_DOCKER_VERSION=1.1.2

# Install useful tools
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg nano zsh-syntax-highlighting less postgresql-client build-essential git && \
  rm -rf /var/lib/apt/lists/*

# Install zsh-in-docker
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v${ZSH_IN_DOCKER_VERSION}/zsh-in-docker.sh)" -- \
  -t clean \
  -p git \
  -p node \
  -p yarn \
  -p history \
  -p https://github.com/zsh-users/zsh-autosuggestions \
  -p https://github.com/zsh-users/zsh-completions
RUN echo "source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> /root/.zshrc

RUN python -m pip install --upgrade pip
RUN pip install autopep8 flake8 black yapf bandit flake8 mypy pycodestyle pydocstyle pylint

# Working directory inside container
WORKDIR /app

EXPOSE  11338

CMD [ "/bin/zsh", "-c" ]
