FROM golang:1.19-bullseye

ARG ZSH_IN_DOCKER_VERSION=1.1.2

# Install useful tools
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg nano zsh-syntax-highlighting less build-essential ocl-icd-opencl-dev && \
  rm -rf /var/lib/apt/lists/*

# Install zsh-in-docker
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v${ZSH_IN_DOCKER_VERSION}/zsh-in-docker.sh)" -- \
  -t clean \
  -p git \
  -p node \
  -p yarn \
  -p history \
  -p https://github.com/zsh-users/zsh-autosuggestions \
  -p https://github.com/zsh-users/zsh-completions
RUN echo "source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> /root/.zshrc

# Working directory inside container
WORKDIR /app

EXPOSE  3000

RUN go install github.com/go-delve/delve/cmd/dlv@latest && \
  go install github.com/Khan/genqlient@latest && \
  go install -v github.com/ramya-rao-a/go-outline@latest && \
  go install -v golang.org/x/tools/gopls@latest && \
  go install -v golang.org/x/tools/cmd/goimports@latest && \
  wget https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh  && \
  chmod +x install.sh && \
  ./install.sh -b /usr/local/bin v1.49.0 && \
  rm -f install.sh

ENV CGO_ENABLED=1
ENV LC_ALL=C

CMD [ "/bin/zsh", "-c" ]