// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/adhocaccount"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/block"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/predicate"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/wallet"
	"github.com/google/uuid"
)

// AdhocAccountQuery is the builder for querying AdhocAccount entities.
type AdhocAccountQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AdhocAccount
	withWallet *WalletQuery
	withBlocks *BlockQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdhocAccountQuery builder.
func (aaq *AdhocAccountQuery) Where(ps ...predicate.AdhocAccount) *AdhocAccountQuery {
	aaq.predicates = append(aaq.predicates, ps...)
	return aaq
}

// Limit adds a limit step to the query.
func (aaq *AdhocAccountQuery) Limit(limit int) *AdhocAccountQuery {
	aaq.limit = &limit
	return aaq
}

// Offset adds an offset step to the query.
func (aaq *AdhocAccountQuery) Offset(offset int) *AdhocAccountQuery {
	aaq.offset = &offset
	return aaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aaq *AdhocAccountQuery) Unique(unique bool) *AdhocAccountQuery {
	aaq.unique = &unique
	return aaq
}

// Order adds an order step to the query.
func (aaq *AdhocAccountQuery) Order(o ...OrderFunc) *AdhocAccountQuery {
	aaq.order = append(aaq.order, o...)
	return aaq
}

// QueryWallet chains the current query on the "wallet" edge.
func (aaq *AdhocAccountQuery) QueryWallet() *WalletQuery {
	query := &WalletQuery{config: aaq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adhocaccount.Table, adhocaccount.FieldID, selector),
			sqlgraph.To(wallet.Table, wallet.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adhocaccount.WalletTable, adhocaccount.WalletColumn),
		)
		fromU = sqlgraph.SetNeighbors(aaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBlocks chains the current query on the "blocks" edge.
func (aaq *AdhocAccountQuery) QueryBlocks() *BlockQuery {
	query := &BlockQuery{config: aaq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adhocaccount.Table, adhocaccount.FieldID, selector),
			sqlgraph.To(block.Table, block.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, adhocaccount.BlocksTable, adhocaccount.BlocksColumn),
		)
		fromU = sqlgraph.SetNeighbors(aaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AdhocAccount entity from the query.
// Returns a *NotFoundError when no AdhocAccount was found.
func (aaq *AdhocAccountQuery) First(ctx context.Context) (*AdhocAccount, error) {
	nodes, err := aaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adhocaccount.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aaq *AdhocAccountQuery) FirstX(ctx context.Context) *AdhocAccount {
	node, err := aaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdhocAccount ID from the query.
// Returns a *NotFoundError when no AdhocAccount ID was found.
func (aaq *AdhocAccountQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adhocaccount.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aaq *AdhocAccountQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := aaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdhocAccount entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdhocAccount entity is found.
// Returns a *NotFoundError when no AdhocAccount entities are found.
func (aaq *AdhocAccountQuery) Only(ctx context.Context) (*AdhocAccount, error) {
	nodes, err := aaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adhocaccount.Label}
	default:
		return nil, &NotSingularError{adhocaccount.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aaq *AdhocAccountQuery) OnlyX(ctx context.Context) *AdhocAccount {
	node, err := aaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdhocAccount ID in the query.
// Returns a *NotSingularError when more than one AdhocAccount ID is found.
// Returns a *NotFoundError when no entities are found.
func (aaq *AdhocAccountQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adhocaccount.Label}
	default:
		err = &NotSingularError{adhocaccount.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aaq *AdhocAccountQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := aaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdhocAccounts.
func (aaq *AdhocAccountQuery) All(ctx context.Context) ([]*AdhocAccount, error) {
	if err := aaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aaq *AdhocAccountQuery) AllX(ctx context.Context) []*AdhocAccount {
	nodes, err := aaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdhocAccount IDs.
func (aaq *AdhocAccountQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := aaq.Select(adhocaccount.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aaq *AdhocAccountQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := aaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aaq *AdhocAccountQuery) Count(ctx context.Context) (int, error) {
	if err := aaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aaq *AdhocAccountQuery) CountX(ctx context.Context) int {
	count, err := aaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aaq *AdhocAccountQuery) Exist(ctx context.Context) (bool, error) {
	if err := aaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aaq *AdhocAccountQuery) ExistX(ctx context.Context) bool {
	exist, err := aaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdhocAccountQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aaq *AdhocAccountQuery) Clone() *AdhocAccountQuery {
	if aaq == nil {
		return nil
	}
	return &AdhocAccountQuery{
		config:     aaq.config,
		limit:      aaq.limit,
		offset:     aaq.offset,
		order:      append([]OrderFunc{}, aaq.order...),
		predicates: append([]predicate.AdhocAccount{}, aaq.predicates...),
		withWallet: aaq.withWallet.Clone(),
		withBlocks: aaq.withBlocks.Clone(),
		// clone intermediate query.
		sql:    aaq.sql.Clone(),
		path:   aaq.path,
		unique: aaq.unique,
	}
}

// WithWallet tells the query-builder to eager-load the nodes that are connected to
// the "wallet" edge. The optional arguments are used to configure the query builder of the edge.
func (aaq *AdhocAccountQuery) WithWallet(opts ...func(*WalletQuery)) *AdhocAccountQuery {
	query := &WalletQuery{config: aaq.config}
	for _, opt := range opts {
		opt(query)
	}
	aaq.withWallet = query
	return aaq
}

// WithBlocks tells the query-builder to eager-load the nodes that are connected to
// the "blocks" edge. The optional arguments are used to configure the query builder of the edge.
func (aaq *AdhocAccountQuery) WithBlocks(opts ...func(*BlockQuery)) *AdhocAccountQuery {
	query := &BlockQuery{config: aaq.config}
	for _, opt := range opts {
		opt(query)
	}
	aaq.withBlocks = query
	return aaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WalletID uuid.UUID `json:"wallet_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdhocAccount.Query().
//		GroupBy(adhocaccount.FieldWalletID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aaq *AdhocAccountQuery) GroupBy(field string, fields ...string) *AdhocAccountGroupBy {
	grbuild := &AdhocAccountGroupBy{config: aaq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aaq.sqlQuery(ctx), nil
	}
	grbuild.label = adhocaccount.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WalletID uuid.UUID `json:"wallet_id,omitempty"`
//	}
//
//	client.AdhocAccount.Query().
//		Select(adhocaccount.FieldWalletID).
//		Scan(ctx, &v)
func (aaq *AdhocAccountQuery) Select(fields ...string) *AdhocAccountSelect {
	aaq.fields = append(aaq.fields, fields...)
	selbuild := &AdhocAccountSelect{AdhocAccountQuery: aaq}
	selbuild.label = adhocaccount.Label
	selbuild.flds, selbuild.scan = &aaq.fields, selbuild.Scan
	return selbuild
}

func (aaq *AdhocAccountQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aaq.fields {
		if !adhocaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aaq.path != nil {
		prev, err := aaq.path(ctx)
		if err != nil {
			return err
		}
		aaq.sql = prev
	}
	return nil
}

func (aaq *AdhocAccountQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdhocAccount, error) {
	var (
		nodes       = []*AdhocAccount{}
		_spec       = aaq.querySpec()
		loadedTypes = [2]bool{
			aaq.withWallet != nil,
			aaq.withBlocks != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*AdhocAccount).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &AdhocAccount{config: aaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aaq.withWallet; query != nil {
		if err := aaq.loadWallet(ctx, query, nodes, nil,
			func(n *AdhocAccount, e *Wallet) { n.Edges.Wallet = e }); err != nil {
			return nil, err
		}
	}
	if query := aaq.withBlocks; query != nil {
		if err := aaq.loadBlocks(ctx, query, nodes,
			func(n *AdhocAccount) { n.Edges.Blocks = []*Block{} },
			func(n *AdhocAccount, e *Block) { n.Edges.Blocks = append(n.Edges.Blocks, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aaq *AdhocAccountQuery) loadWallet(ctx context.Context, query *WalletQuery, nodes []*AdhocAccount, init func(*AdhocAccount), assign func(*AdhocAccount, *Wallet)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*AdhocAccount)
	for i := range nodes {
		fk := nodes[i].WalletID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(wallet.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "wallet_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (aaq *AdhocAccountQuery) loadBlocks(ctx context.Context, query *BlockQuery, nodes []*AdhocAccount, init func(*AdhocAccount), assign func(*AdhocAccount, *Block)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*AdhocAccount)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.Where(predicate.Block(func(s *sql.Selector) {
		s.Where(sql.InValues(adhocaccount.BlocksColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AdhocAccountID
		if fk == nil {
			return fmt.Errorf(`foreign-key "adhoc_account_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "adhoc_account_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (aaq *AdhocAccountQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aaq.querySpec()
	_spec.Node.Columns = aaq.fields
	if len(aaq.fields) > 0 {
		_spec.Unique = aaq.unique != nil && *aaq.unique
	}
	return sqlgraph.CountNodes(ctx, aaq.driver, _spec)
}

func (aaq *AdhocAccountQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := aaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (aaq *AdhocAccountQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   adhocaccount.Table,
			Columns: adhocaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: adhocaccount.FieldID,
			},
		},
		From:   aaq.sql,
		Unique: true,
	}
	if unique := aaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := aaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adhocaccount.FieldID)
		for i := range fields {
			if fields[i] != adhocaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aaq *AdhocAccountQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aaq.driver.Dialect())
	t1 := builder.Table(adhocaccount.Table)
	columns := aaq.fields
	if len(columns) == 0 {
		columns = adhocaccount.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aaq.sql != nil {
		selector = aaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aaq.unique != nil && *aaq.unique {
		selector.Distinct()
	}
	for _, p := range aaq.predicates {
		p(selector)
	}
	for _, p := range aaq.order {
		p(selector)
	}
	if offset := aaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdhocAccountGroupBy is the group-by builder for AdhocAccount entities.
type AdhocAccountGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aagb *AdhocAccountGroupBy) Aggregate(fns ...AggregateFunc) *AdhocAccountGroupBy {
	aagb.fns = append(aagb.fns, fns...)
	return aagb
}

// Scan applies the group-by query and scans the result into the given value.
func (aagb *AdhocAccountGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aagb.path(ctx)
	if err != nil {
		return err
	}
	aagb.sql = query
	return aagb.sqlScan(ctx, v)
}

func (aagb *AdhocAccountGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range aagb.fields {
		if !adhocaccount.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := aagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aagb *AdhocAccountGroupBy) sqlQuery() *sql.Selector {
	selector := aagb.sql.Select()
	aggregation := make([]string, 0, len(aagb.fns))
	for _, fn := range aagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(aagb.fields)+len(aagb.fns))
		for _, f := range aagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(aagb.fields...)...)
}

// AdhocAccountSelect is the builder for selecting fields of AdhocAccount entities.
type AdhocAccountSelect struct {
	*AdhocAccountQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (aas *AdhocAccountSelect) Scan(ctx context.Context, v interface{}) error {
	if err := aas.prepareQuery(ctx); err != nil {
		return err
	}
	aas.sql = aas.AdhocAccountQuery.sqlQuery(ctx)
	return aas.sqlScan(ctx, v)
}

func (aas *AdhocAccountSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := aas.sql.Query()
	if err := aas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
