// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/adhocaccount"
)

// AdhocAccount is the model entity for the AdhocAccount schema.
type AdhocAccount struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AdhocAccount) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case adhocaccount.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type AdhocAccount", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AdhocAccount fields.
func (aa *AdhocAccount) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case adhocaccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			aa.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this AdhocAccount.
// Note that you need to call AdhocAccount.Unwrap() before calling this method if this AdhocAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (aa *AdhocAccount) Update() *AdhocAccountUpdateOne {
	return (&AdhocAccountClient{config: aa.config}).UpdateOne(aa)
}

// Unwrap unwraps the AdhocAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (aa *AdhocAccount) Unwrap() *AdhocAccount {
	_tx, ok := aa.config.driver.(*txDriver)
	if !ok {
		panic("ent: AdhocAccount is not a transactional entity")
	}
	aa.config.driver = _tx.drv
	return aa
}

// String implements the fmt.Stringer.
func (aa *AdhocAccount) String() string {
	var builder strings.Builder
	builder.WriteString("AdhocAccount(")
	builder.WriteString(fmt.Sprintf("id=%v", aa.ID))
	builder.WriteByte(')')
	return builder.String()
}

// AdhocAccounts is a parsable slice of AdhocAccount.
type AdhocAccounts []*AdhocAccount

func (aa AdhocAccounts) config(cfg config) {
	for _i := range aa {
		aa[_i].config = cfg
	}
}
