// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/adhocaccount"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/predicate"
)

// AdhocAccountDelete is the builder for deleting a AdhocAccount entity.
type AdhocAccountDelete struct {
	config
	hooks    []Hook
	mutation *AdhocAccountMutation
}

// Where appends a list predicates to the AdhocAccountDelete builder.
func (aad *AdhocAccountDelete) Where(ps ...predicate.AdhocAccount) *AdhocAccountDelete {
	aad.mutation.Where(ps...)
	return aad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aad *AdhocAccountDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aad.hooks) == 0 {
		affected, err = aad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdhocAccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aad.mutation = mutation
			affected, err = aad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aad.hooks) - 1; i >= 0; i-- {
			if aad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (aad *AdhocAccountDelete) ExecX(ctx context.Context) int {
	n, err := aad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aad *AdhocAccountDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: adhocaccount.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: adhocaccount.FieldID,
			},
		},
	}
	if ps := aad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, aad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// AdhocAccountDeleteOne is the builder for deleting a single AdhocAccount entity.
type AdhocAccountDeleteOne struct {
	aad *AdhocAccountDelete
}

// Exec executes the deletion query.
func (aado *AdhocAccountDeleteOne) Exec(ctx context.Context) error {
	n, err := aado.aad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adhocaccount.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aado *AdhocAccountDeleteOne) ExecX(ctx context.Context) {
	aado.aad.ExecX(ctx)
}
