// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/adhocaccount"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/block"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/predicate"
	"github.com/appditto/pippin_nano_wallet/libs/database/ent/wallet"
	"github.com/google/uuid"
)

// AdhocAccountUpdate is the builder for updating AdhocAccount entities.
type AdhocAccountUpdate struct {
	config
	hooks    []Hook
	mutation *AdhocAccountMutation
}

// Where appends a list predicates to the AdhocAccountUpdate builder.
func (aau *AdhocAccountUpdate) Where(ps ...predicate.AdhocAccount) *AdhocAccountUpdate {
	aau.mutation.Where(ps...)
	return aau
}

// SetWalletID sets the "wallet_id" field.
func (aau *AdhocAccountUpdate) SetWalletID(u uuid.UUID) *AdhocAccountUpdate {
	aau.mutation.SetWalletID(u)
	return aau
}

// SetAddress sets the "address" field.
func (aau *AdhocAccountUpdate) SetAddress(s string) *AdhocAccountUpdate {
	aau.mutation.SetAddress(s)
	return aau
}

// SetPrivateKey sets the "private_key" field.
func (aau *AdhocAccountUpdate) SetPrivateKey(s string) *AdhocAccountUpdate {
	aau.mutation.SetPrivateKey(s)
	return aau
}

// SetWork sets the "work" field.
func (aau *AdhocAccountUpdate) SetWork(b bool) *AdhocAccountUpdate {
	aau.mutation.SetWork(b)
	return aau
}

// SetNillableWork sets the "work" field if the given value is not nil.
func (aau *AdhocAccountUpdate) SetNillableWork(b *bool) *AdhocAccountUpdate {
	if b != nil {
		aau.SetWork(*b)
	}
	return aau
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (aau *AdhocAccountUpdate) SetWallet(w *Wallet) *AdhocAccountUpdate {
	return aau.SetWalletID(w.ID)
}

// AddBlockIDs adds the "blocks" edge to the Block entity by IDs.
func (aau *AdhocAccountUpdate) AddBlockIDs(ids ...uuid.UUID) *AdhocAccountUpdate {
	aau.mutation.AddBlockIDs(ids...)
	return aau
}

// AddBlocks adds the "blocks" edges to the Block entity.
func (aau *AdhocAccountUpdate) AddBlocks(b ...*Block) *AdhocAccountUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return aau.AddBlockIDs(ids...)
}

// Mutation returns the AdhocAccountMutation object of the builder.
func (aau *AdhocAccountUpdate) Mutation() *AdhocAccountMutation {
	return aau.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (aau *AdhocAccountUpdate) ClearWallet() *AdhocAccountUpdate {
	aau.mutation.ClearWallet()
	return aau
}

// ClearBlocks clears all "blocks" edges to the Block entity.
func (aau *AdhocAccountUpdate) ClearBlocks() *AdhocAccountUpdate {
	aau.mutation.ClearBlocks()
	return aau
}

// RemoveBlockIDs removes the "blocks" edge to Block entities by IDs.
func (aau *AdhocAccountUpdate) RemoveBlockIDs(ids ...uuid.UUID) *AdhocAccountUpdate {
	aau.mutation.RemoveBlockIDs(ids...)
	return aau
}

// RemoveBlocks removes "blocks" edges to Block entities.
func (aau *AdhocAccountUpdate) RemoveBlocks(b ...*Block) *AdhocAccountUpdate {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return aau.RemoveBlockIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aau *AdhocAccountUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aau.hooks) == 0 {
		if err = aau.check(); err != nil {
			return 0, err
		}
		affected, err = aau.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdhocAccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aau.check(); err != nil {
				return 0, err
			}
			aau.mutation = mutation
			affected, err = aau.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aau.hooks) - 1; i >= 0; i-- {
			if aau.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aau.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aau.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (aau *AdhocAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := aau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aau *AdhocAccountUpdate) Exec(ctx context.Context) error {
	_, err := aau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aau *AdhocAccountUpdate) ExecX(ctx context.Context) {
	if err := aau.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aau *AdhocAccountUpdate) check() error {
	if v, ok := aau.mutation.Address(); ok {
		if err := adhocaccount.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "AdhocAccount.address": %w`, err)}
		}
	}
	if v, ok := aau.mutation.PrivateKey(); ok {
		if err := adhocaccount.PrivateKeyValidator(v); err != nil {
			return &ValidationError{Name: "private_key", err: fmt.Errorf(`ent: validator failed for field "AdhocAccount.private_key": %w`, err)}
		}
	}
	if _, ok := aau.mutation.WalletID(); aau.mutation.WalletCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "AdhocAccount.wallet"`)
	}
	return nil
}

func (aau *AdhocAccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   adhocaccount.Table,
			Columns: adhocaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: adhocaccount.FieldID,
			},
		},
	}
	if ps := aau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aau.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: adhocaccount.FieldAddress,
		})
	}
	if value, ok := aau.mutation.PrivateKey(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: adhocaccount.FieldPrivateKey,
		})
	}
	if value, ok := aau.mutation.Work(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: adhocaccount.FieldWork,
		})
	}
	if aau.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adhocaccount.WalletTable,
			Columns: []string{adhocaccount.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: wallet.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aau.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adhocaccount.WalletTable,
			Columns: []string{adhocaccount.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: wallet.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aau.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adhocaccount.BlocksTable,
			Columns: []string{adhocaccount.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: block.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aau.mutation.RemovedBlocksIDs(); len(nodes) > 0 && !aau.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adhocaccount.BlocksTable,
			Columns: []string{adhocaccount.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: block.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aau.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adhocaccount.BlocksTable,
			Columns: []string{adhocaccount.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: block.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adhocaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AdhocAccountUpdateOne is the builder for updating a single AdhocAccount entity.
type AdhocAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdhocAccountMutation
}

// SetWalletID sets the "wallet_id" field.
func (aauo *AdhocAccountUpdateOne) SetWalletID(u uuid.UUID) *AdhocAccountUpdateOne {
	aauo.mutation.SetWalletID(u)
	return aauo
}

// SetAddress sets the "address" field.
func (aauo *AdhocAccountUpdateOne) SetAddress(s string) *AdhocAccountUpdateOne {
	aauo.mutation.SetAddress(s)
	return aauo
}

// SetPrivateKey sets the "private_key" field.
func (aauo *AdhocAccountUpdateOne) SetPrivateKey(s string) *AdhocAccountUpdateOne {
	aauo.mutation.SetPrivateKey(s)
	return aauo
}

// SetWork sets the "work" field.
func (aauo *AdhocAccountUpdateOne) SetWork(b bool) *AdhocAccountUpdateOne {
	aauo.mutation.SetWork(b)
	return aauo
}

// SetNillableWork sets the "work" field if the given value is not nil.
func (aauo *AdhocAccountUpdateOne) SetNillableWork(b *bool) *AdhocAccountUpdateOne {
	if b != nil {
		aauo.SetWork(*b)
	}
	return aauo
}

// SetWallet sets the "wallet" edge to the Wallet entity.
func (aauo *AdhocAccountUpdateOne) SetWallet(w *Wallet) *AdhocAccountUpdateOne {
	return aauo.SetWalletID(w.ID)
}

// AddBlockIDs adds the "blocks" edge to the Block entity by IDs.
func (aauo *AdhocAccountUpdateOne) AddBlockIDs(ids ...uuid.UUID) *AdhocAccountUpdateOne {
	aauo.mutation.AddBlockIDs(ids...)
	return aauo
}

// AddBlocks adds the "blocks" edges to the Block entity.
func (aauo *AdhocAccountUpdateOne) AddBlocks(b ...*Block) *AdhocAccountUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return aauo.AddBlockIDs(ids...)
}

// Mutation returns the AdhocAccountMutation object of the builder.
func (aauo *AdhocAccountUpdateOne) Mutation() *AdhocAccountMutation {
	return aauo.mutation
}

// ClearWallet clears the "wallet" edge to the Wallet entity.
func (aauo *AdhocAccountUpdateOne) ClearWallet() *AdhocAccountUpdateOne {
	aauo.mutation.ClearWallet()
	return aauo
}

// ClearBlocks clears all "blocks" edges to the Block entity.
func (aauo *AdhocAccountUpdateOne) ClearBlocks() *AdhocAccountUpdateOne {
	aauo.mutation.ClearBlocks()
	return aauo
}

// RemoveBlockIDs removes the "blocks" edge to Block entities by IDs.
func (aauo *AdhocAccountUpdateOne) RemoveBlockIDs(ids ...uuid.UUID) *AdhocAccountUpdateOne {
	aauo.mutation.RemoveBlockIDs(ids...)
	return aauo
}

// RemoveBlocks removes "blocks" edges to Block entities.
func (aauo *AdhocAccountUpdateOne) RemoveBlocks(b ...*Block) *AdhocAccountUpdateOne {
	ids := make([]uuid.UUID, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return aauo.RemoveBlockIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aauo *AdhocAccountUpdateOne) Select(field string, fields ...string) *AdhocAccountUpdateOne {
	aauo.fields = append([]string{field}, fields...)
	return aauo
}

// Save executes the query and returns the updated AdhocAccount entity.
func (aauo *AdhocAccountUpdateOne) Save(ctx context.Context) (*AdhocAccount, error) {
	var (
		err  error
		node *AdhocAccount
	)
	if len(aauo.hooks) == 0 {
		if err = aauo.check(); err != nil {
			return nil, err
		}
		node, err = aauo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AdhocAccountMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aauo.check(); err != nil {
				return nil, err
			}
			aauo.mutation = mutation
			node, err = aauo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(aauo.hooks) - 1; i >= 0; i-- {
			if aauo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aauo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, aauo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*AdhocAccount)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AdhocAccountMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (aauo *AdhocAccountUpdateOne) SaveX(ctx context.Context) *AdhocAccount {
	node, err := aauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aauo *AdhocAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := aauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aauo *AdhocAccountUpdateOne) ExecX(ctx context.Context) {
	if err := aauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aauo *AdhocAccountUpdateOne) check() error {
	if v, ok := aauo.mutation.Address(); ok {
		if err := adhocaccount.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "AdhocAccount.address": %w`, err)}
		}
	}
	if v, ok := aauo.mutation.PrivateKey(); ok {
		if err := adhocaccount.PrivateKeyValidator(v); err != nil {
			return &ValidationError{Name: "private_key", err: fmt.Errorf(`ent: validator failed for field "AdhocAccount.private_key": %w`, err)}
		}
	}
	if _, ok := aauo.mutation.WalletID(); aauo.mutation.WalletCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "AdhocAccount.wallet"`)
	}
	return nil
}

func (aauo *AdhocAccountUpdateOne) sqlSave(ctx context.Context) (_node *AdhocAccount, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   adhocaccount.Table,
			Columns: adhocaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: adhocaccount.FieldID,
			},
		},
	}
	id, ok := aauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdhocAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adhocaccount.FieldID)
		for _, f := range fields {
			if !adhocaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adhocaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aauo.mutation.Address(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: adhocaccount.FieldAddress,
		})
	}
	if value, ok := aauo.mutation.PrivateKey(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: adhocaccount.FieldPrivateKey,
		})
	}
	if value, ok := aauo.mutation.Work(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: adhocaccount.FieldWork,
		})
	}
	if aauo.mutation.WalletCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adhocaccount.WalletTable,
			Columns: []string{adhocaccount.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: wallet.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aauo.mutation.WalletIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   adhocaccount.WalletTable,
			Columns: []string{adhocaccount.WalletColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: wallet.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aauo.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adhocaccount.BlocksTable,
			Columns: []string{adhocaccount.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: block.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aauo.mutation.RemovedBlocksIDs(); len(nodes) > 0 && !aauo.mutation.BlocksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adhocaccount.BlocksTable,
			Columns: []string{adhocaccount.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: block.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aauo.mutation.BlocksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   adhocaccount.BlocksTable,
			Columns: []string{adhocaccount.BlocksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: block.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AdhocAccount{config: aauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adhocaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
