// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "address", Type: field.TypeString, Size: 65},
		{Name: "account_index", Type: field.TypeInt},
		{Name: "work", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "wallet_id", Type: field.TypeUUID},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_wallets_accounts",
				Columns:    []*schema.Column{AccountsColumns[5]},
				RefColumns: []*schema.Column{WalletsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "account_wallet_id",
				Unique:  false,
				Columns: []*schema.Column{AccountsColumns[5]},
			},
			{
				Name:    "account_wallet_id_address_account_index",
				Unique:  true,
				Columns: []*schema.Column{AccountsColumns[5], AccountsColumns[1], AccountsColumns[2]},
			},
		},
	}
	// AdhocAccountsColumns holds the columns for the "adhoc_accounts" table.
	AdhocAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "address", Type: field.TypeString, Size: 65},
		{Name: "private_key", Type: field.TypeString, Size: 128},
		{Name: "work", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "wallet_id", Type: field.TypeUUID},
	}
	// AdhocAccountsTable holds the schema information for the "adhoc_accounts" table.
	AdhocAccountsTable = &schema.Table{
		Name:       "adhoc_accounts",
		Columns:    AdhocAccountsColumns,
		PrimaryKey: []*schema.Column{AdhocAccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "adhoc_accounts_wallets_adhoc_accounts",
				Columns:    []*schema.Column{AdhocAccountsColumns[5]},
				RefColumns: []*schema.Column{WalletsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "adhocaccount_wallet_id",
				Unique:  false,
				Columns: []*schema.Column{AdhocAccountsColumns[5]},
			},
			{
				Name:    "adhocaccount_wallet_id_address_private_key",
				Unique:  true,
				Columns: []*schema.Column{AdhocAccountsColumns[5], AdhocAccountsColumns[1], AdhocAccountsColumns[2]},
			},
		},
	}
	// BlocksColumns holds the columns for the "blocks" table.
	BlocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "block_hash", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "block", Type: field.TypeJSON},
		{Name: "send_id", Type: field.TypeString, Nullable: true, Size: 64},
		{Name: "subtype", Type: field.TypeString, Size: 10},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeUUID},
		{Name: "adhoc_account_id", Type: field.TypeUUID},
	}
	// BlocksTable holds the schema information for the "blocks" table.
	BlocksTable = &schema.Table{
		Name:       "blocks",
		Columns:    BlocksColumns,
		PrimaryKey: []*schema.Column{BlocksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "blocks_accounts_blocks",
				Columns:    []*schema.Column{BlocksColumns[6]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "blocks_adhoc_accounts_blocks",
				Columns:    []*schema.Column{BlocksColumns[7]},
				RefColumns: []*schema.Column{AdhocAccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "block_account_id",
				Unique:  false,
				Columns: []*schema.Column{BlocksColumns[6]},
			},
			{
				Name:    "block_adhoc_account_id",
				Unique:  false,
				Columns: []*schema.Column{BlocksColumns[7]},
			},
			{
				Name:    "block_send_id",
				Unique:  false,
				Columns: []*schema.Column{BlocksColumns[3]},
			},
			{
				Name:    "block_account_id_send_id",
				Unique:  true,
				Columns: []*schema.Column{BlocksColumns[6], BlocksColumns[3]},
			},
		},
	}
	// WalletsColumns holds the columns for the "wallets" table.
	WalletsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "seed", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "representative", Type: field.TypeString, Nullable: true, Size: 65},
		{Name: "encrypted", Type: field.TypeBool, Default: false},
		{Name: "work", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// WalletsTable holds the schema information for the "wallets" table.
	WalletsTable = &schema.Table{
		Name:       "wallets",
		Columns:    WalletsColumns,
		PrimaryKey: []*schema.Column{WalletsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		AdhocAccountsTable,
		BlocksTable,
		WalletsTable,
	}
)

func init() {
	AccountsTable.ForeignKeys[0].RefTable = WalletsTable
	AccountsTable.Annotation = &entsql.Annotation{
		Table: "accounts",
	}
	AdhocAccountsTable.ForeignKeys[0].RefTable = WalletsTable
	AdhocAccountsTable.Annotation = &entsql.Annotation{
		Table: "adhoc_accounts",
	}
	BlocksTable.ForeignKeys[0].RefTable = AccountsTable
	BlocksTable.ForeignKeys[1].RefTable = AdhocAccountsTable
	BlocksTable.Annotation = &entsql.Annotation{
		Table: "blocks",
	}
	WalletsTable.Annotation = &entsql.Annotation{
		Table: "wallets",
	}
}
