// Code generated by ent, DO NOT EDIT.

package adhocaccount

const (
	// Label holds the string label denoting the adhocaccount type in the database.
	Label = "adhoc_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the adhocaccount in the database.
	Table = "adhoc_accounts"
)

// Columns holds all SQL columns for adhocaccount fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
