// Code generated by ent, DO NOT EDIT.

package wallet

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the wallet type in the database.
	Label = "wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSeed holds the string denoting the seed field in the database.
	FieldSeed = "seed"
	// FieldRepresentative holds the string denoting the representative field in the database.
	FieldRepresentative = "representative"
	// FieldEncrypted holds the string denoting the encrypted field in the database.
	FieldEncrypted = "encrypted"
	// FieldWork holds the string denoting the work field in the database.
	FieldWork = "work"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// Table holds the table name of the wallet in the database.
	Table = "wallets"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "wallet_id"
)

// Columns holds all SQL columns for wallet fields.
var Columns = []string{
	FieldID,
	FieldSeed,
	FieldRepresentative,
	FieldEncrypted,
	FieldWork,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SeedValidator is a validator for the "seed" field. It is called by the builders before save.
	SeedValidator func(string) error
	// RepresentativeValidator is a validator for the "representative" field. It is called by the builders before save.
	RepresentativeValidator func(string) error
	// DefaultEncrypted holds the default value on creation for the "encrypted" field.
	DefaultEncrypted bool
	// DefaultWork holds the default value on creation for the "work" field.
	DefaultWork bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
